name: Repository Events
on: 
    push: 
        branches:
            - main
            - "feature/*"  #matches feature/featA or feature/featb. Not feature/feata/featb.
            - "feature/**" #matches feature/featA or feature/featb or feature/feata/featb.
            - "!feature/featA"  #this will ignore feature/featA.  Order is important
        #branches-ignore:
        #    - develop
        tags: 
            - v1.* #match 1.1, 1.2.....
            - "!v1.1.1"
        paths:
            - "**.js"
            - "!app.js"
    pull_request:
        types: [opened, assigned, reopened, synchronize]
        branches:
            - man
        paths:
            - "**.js"
    issues:
        types: [opened]
jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - run:
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v3
