name: Manually Triggered
on:
    workflow_dispatch:
        inputs:
            string: 
                description: A string input
                type: string
                required: true
                default: "Default value"
            number:
                description: A number input
                type: number
                default: 4

jobs:
    log-info:
        runs-on: ubuntu-latest
        steps:
            - run: echo $GITHUB_REF
            - run: |
                echo "String: ${{ inputs.string }}"
                echo "String: ${{ inputs.number }}"